



  import React, { useState } from 'react'
  
  export default function positiveSentences() {
    const [Sentences, setSentences] = useState([[
        "Her gün kendimi biraz daha çok seviyorum.",
        "Başarıya giden yolun anahtarı olan güç bende.",
        "Hayatın her anının tadını çıkarıyorum.",
        "Kendimi olduğum gibi kabul ediyorum ve değerli hissediyorum.",
        "Her zorlukla karşılaştığımda, daha güçlü ve dirençli hale geliyorum.",
        "Geleceğe umutla bakıyor ve her gün daha iyisini yapabilmek için çabalıyorum.",
        "Kendime olan güvenim sınırsız.",
        "Başkalarının benim hakkımda düşündükleri, beni tanımlamaz.",
        "Her gün bir adım daha ileriye gidiyorum ve kendimi geliştiriyorum.",
        "İçimdeki potansiyelin farkındayım ve onu en iyi şekilde değerlendiriyorum.",
        "Geçmişimdeki hatalar beni yıldırmaz, aksine daha da güçlendirir.",
        "Hayatta karşılaştığım zorluklar, güçlü olmamı sağlar.",
        "Her yeni gün, yeni bir fırsat ve yeni bir başlangıçtır.",
        "Kendime güvenmek, en büyük güç kaynağımdır.",
        "Başarı için gerekli olan tüm potansiyel bende mevcut.",
        "Kendimle barışık bir şekilde yaşıyorum.",
        "Her gün biraz daha olgunlaşıyor ve büyüyorum.",
        "Kendime olan inancım, her şeyin üstesinden gelmemi sağlar.",
        "Hayatta önemli olan sadece sonuç değil, aynı zamanda yolculuktur.",
        "Başkalarına yardım ederek, kendimi daha da iyi hissediyorum.",
        "Kendimi sevmek, hayatımın her alanında başarılı olmamı sağlar.",
        "Olumlu düşünce tarzım, hayatımı daha da pozitif hale getirir.",
        "Kendime dürüst davranıyor ve kendi doğrularımla yaşıyorum.",
        "Geleceğe dair hayallerim, beni her gün daha da motive eder.",
        "Kendimi sevgiyle besliyor ve olumlu enerjiyle doluyorum.",
        "Her gün daha da fazla özgüven kazanıyorum.",
        "Kendime olan saygım, başkalarının beni nasıl gördüğünden daha önemlidir.",
        "Olumsuz düşünceleri geride bırakıyor ve pozitif enerjimi yükseltiyorum.",
        "Kendimi olduğum gibi kabul ediyor ve mükemmel olduğumu biliyorum.",
        "Kendimi keşfetmek için zaman ayırıyor ve içsel huzurumu buluyorum.",
        "Her gün biraz daha fazla mutluluk ve huzur hissediyorum.",
        "Kendimi gerçekleştirmek için gereken her şeye sahibim.",
        "Hayatımın yönetmeni benim ve en iyi performansı sergiliyorum.",
        "Kendime duyduğum güven, hayatımın her alanında başarıyı getirir.",
        "Her gün biraz daha fazla pozitif enerjiye sahip oluyorum.",
        "Başarı için sadece bir başlangıç ​​yapmam yeterli.",
        "Olumlu düşüncelerim, olumlu sonuçlar doğurur.",
        "Hayatta başarılı olmak için gereken her şeye sahibim.",
        "Kendimi sevgiyle dolduruyor ve bu sevgiyi etrafıma yayıyorum.",
        "Gelecek hakkında endişelenmek yerine, ona umutla bakıyorum.",
        "Kendimi en iyi versiyonumla ifade etmek için her gün çabalıyorum.",
        "Kendimle ilgili olumsuz düşünceleri geride bırakıyorum ve pozitif bir gelecek inşa ediyorum.",
        "Kendime olan güvenim, başkalarının beni kabul etmesini sağlar.",
        "Olumsuzlukları olumluya dönüştürmek için her gün bir fırsattır.",
        "Hayatta önemli olan şey, kaç defa düştüğünüz değil, kaç defa kalktığınızdır.",
        "Kendime karşı dürüst olmak, başarı için temel bir adımdır.",
        "Kendi yeteneklerim ve becerilerimle gurur duyuyorum.",
        "Her gün kendimi biraz daha fazla seviyorum ve kabul ediyorum.",
        "Geleceğe umutla bakıyor ve hayatımda daha iyi günler göreceğime inanıyorum.",
        "Kendimi dış dünyadan bağımsız olarak değerlendiriyor ve takdir ediyorum.",
        "Başarısızlık, bana daha iyiye ulaşma yolunda bir fırsat sunar.",
        "Kendimle barışık bir şekilde yaşamak, huzur ve mutluluk getirir.",
        "Kendimi kısıtlamak yerine, sınırlarımı zorluyor ve büyümeye devam ediyorum.",
        "Her gün biraz daha fazla motivasyon ve enerji hissediyorum.",
        "Hayatta karşılaştığım her zorluk, beni daha da güçlendirir.",
        "Kendimi sevmek, hayatta daha fazla başarı ve mutluluk getirir.",
        "Her gün biraz daha fazla özgür hissediyorum ve hayatımın kontrolünü elime alıyorum.",
        "Gelecekte başarılı olacağıma dair güçlü bir inancım var.",
        "Kendi iç sesimi dinliyor ve kendime güveniyorum.",
        "Her gün biraz daha fazla olumlu düşünce ve enerjiye sahip oluyorum.",
        "Kendime olan inancım, hedeflerime ulaşmamı sağlar.",
        "Hayatta her zaman bir seçeneğim var ve her zaman daha iyisini seçiyorum.",
        "Kendimi olduğum gibi kabul ediyorum ve her gün biraz daha fazla gelişiyorum.",
        "Başkalarının beni değerli hissetmemesi, benim değerli olduğum anlamına gelmez.",
        "Hayatta her şeyi başarabilirim, çünkü ben güçlüyüm.",
        "Olumsuz düşüncelerimi geride bırakıyor ve pozitif bir gelecek inşa ediyorum.",
        "Kendim hakkında olumlu düşünmek, hayatımı daha da güzelleştirir.",
        "Kendimi sevmek, etrafımdaki herkesi daha iyi bir insan yapar.",
        "Geleceğe dair hayallerim, beni her gün daha da motive eder.",
        "Kendimi sevgiyle dolduruyor ve bu sevgiyi başkalarıyla paylaşıyorum.",
        "Her gün biraz daha fazla güven ve cesaret kazanıyorum.",
        "Hayatta karşılaştığım her zorluk, beni daha güçlü ve dayanıklı hale getirir.",
        "Kendimle barışık bir şekilde yaşamak, iç huzurumu bulmamı sağlar.",
        "Kendi değerimi biliyor ve başkalarının bana değer vermesini bekliyorum.",
        "Geleceğe umutla bakıyor ve her gün biraz daha fazla başarıya inanıyorum.",
        "Kendimi olduğum gibi kabul ediyor ve kusurlarımla barışıyorum.",
        "Kendime olan inancım, en büyük gücüm.",
        "Her gün biraz daha fazla olumlu düşünceye sahip oluyorum ve bu beni daha da mutlu ediyor.",
        "Kendimi sevgiyle besliyor ve bu sevgiyi herkese yayıyorum.",
        "Başkalarının beni değerli hissetmemesi, benim değerli olduğum anlamına gelmez.",
        "Her gün biraz daha fazla özgüven kazanıyorum ve kendime olan inancımı güçlendiriyorum.",
        "Kendimi olduğum gibi kabul ediyor ve kendimi seviyorum.",
        "Her zorlukla karşılaştığımda, daha da güçleniyorum.",
        "Geleceğe umutla bakıyor ve en iyinin benim için olduğuna inanıyorum.",
        "Kendimi her gün biraz daha fazla geliştiriyorum ve büyüyorum.",
        "Olumlu düşünce tarzım, hayatımı daha da pozitif hale getiriyor.",
        "Her gün biraz daha fazla neşe ve mutluluk hissediyorum.",
        "Kendime olan güvenim, başarıya giden yolda en büyük rehberim.",
        "Kendimi sevmek, hayatımı daha fazla zevkli hale getiriyor.",
        "Hayatın güzelliklerini fark ediyor ve her anının tadını çıkarıyorum.",
        "Kendimi sevgiyle dolduruyor ve bu sevgiyi çevreme yayıyorum.",
        "Her gün biraz daha fazla özgürlük ve huzur hissediyorum.",
        "Kendimi olduğum gibi kabul ediyor ve kusurlarımı seviyorum.",
        "Geleceğe umutla bakıyor ve her gün daha fazla başarıya inanıyorum.",
        "Kendime güvenmek, her şeyin üstesinden gelmemi sağlar.",
        "Olumsuz düşünceleri geride bırakıyor ve olumlu bir gelecek inşa ediyorum.",
        "Her gün biraz daha fazla pozitif düşünceye sahip oluyorum ve bu beni daha da mutlu ediyor.",
        "Kendimi sevgiyle dolduruyor ve bu sevgiyi başkalarıyla paylaşıyorum.",
        "Başkalarının beni değerli hissetmemesi, benim değerli olduğum anlamına gelmez.",
        "Her gün biraz daha fazla özgüven kazanıyorum ve kendime olan inancımı güçlendiriyorum.",
        "Kendimi olduğum gibi kabul ediyor ve kusurlarımı seviyorum.",
        "Kendime olan inancım, en büyük gücüm.",
        "Her zorlukla karşılaştığımda, daha da güçleniyorum.",
        "Geleceğe umutla bakıyor ve en iyinin benim için olduğuna inanıyorum.",
        "Kendimi her gün biraz daha fazla geliştiriyorum ve büyüyorum.",
        "Olumlu düşünce tarzım, hayatımı daha da pozitif hale getiriyor.",
        "Her gün biraz daha fazla neşe ve mutluluk hissediyorum.",
        "Kendime olan güvenim, başarıya giden yolda en büyük rehberim.",
        "Kendimi sevmek, hayatımı daha fazla zevkli hale getiriyor.",
        "Hayatın güzelliklerini fark ediyor ve her anının tadını çıkarıyorum.",
        "Kendimi sevgiyle dolduruyor ve bu sevgiyi çevreme yayıyorum.",
        "Her gün biraz daha fazla özgürlük ve huzur hissediyorum.",
        "Kendimi olduğum gibi kabul ediyor ve kusurlarımı seviyorum.",
        "Geleceğe umutla bakıyor ve her gün daha fazla başarıya inanıyorum.",
        "Kendime güvenmek, her şeyin üstesinden gelmemi sağlar.",
        "Olumsuz düşünceleri geride bırakıyor ve olumlu bir gelecek inşa ediyorum.",
        "Her gün biraz daha fazla pozitif düşünceye sahip oluyorum ve bu beni daha da mutlu ediyor.",
        "Kendimi sevgiyle dolduruyor ve bu sevgiyi başkalarıyla paylaşıyorum.",
        "Başkalarının beni değerli hissetmemesi, benim değerli olduğum anlamına gelmez.",
        "Her gün biraz daha fazla özgüven kazanıyorum ve kendime olan inancımı güçlendiriyorum.",
        "Kendimi olduğum gibi kabul ediyor ve kusurlarımı seviyorum.",
        "Kendime olan inancım, en büyük gücüm.",
        "Her zorlukla karşılaştığımda, daha da güçleniyorum.",
        "Geleceğe umutla bakıyor ve en iyinin benim için olduğuna inanıyorum.",
        "Kendimi her gün biraz daha fazla geliştiriyorum ve büyüyorum.",
        "Olumlu düşünce tarzım, hayatımı daha da pozitif hale getiriyor.",
        "Her gün biraz daha fazla neşe ve mutluluk hissediyorum.",
        "Kendime olan güvenim, başarıya giden yolda en büyük rehberim.",
        "Kendimi sevmek, hayatımı daha fazla zevkli hale getiriyor.",
        "Hayatın güzelliklerini fark ediyor ve her anının tadını çıkarıyorum.",
        "Kendimi sevgiyle dolduruyor ve bu sevgiyi çevreme yayıyorum.",
        "Her gün biraz daha fazla özgürlük ve huzur hissediyorum.",
        "Kendimi olduğum gibi kabul ediyor ve kusurlarımı seviyorum.",
        "Geleceğe umutla bakıyor ve her gün daha fazla başarıya inanıyorum.",
        "Kendime güvenmek, her şeyin üstesinden gelmemi sağlar.",
        "Olumsuz düşünceleri geride bırakıyor ve olumlu bir gelecek inşa ediyorum.",
        "Her gün biraz daha fazla pozitif düşünceye sahip oluyorum ve bu beni daha da mutlu ediyor.",
        "Kendimi sevgiyle dolduruyor ve bu sevgiyi başkalarıyla paylaşıyorum.",
        "Başkalarının beni değerli hissetmemesi, benim değerli olduğum anlamına gelmez.",
        "Her gün biraz daha fazla özgüven kazanıyorum ve kendime olan inancımı güçlendiriyorum.",
        "Kendimi olduğum gibi kabul ediyor ve kusurlarımı seviyorum.",
        "Kendime olan inancım, en büyük gücüm.",
        "Her zorlukla karşılaştığımda, daha da güçleniyorum.",
        "Geleceğe umutla bakıyor ve en iyinin benim için olduğuna inanıyorum.",
        "Kendimi her gün biraz daha fazla geliştiriyorum ve büyüyorum.",
        "Olumlu düşünce tarzım, hayatımı daha da pozitif hale getiriyor.",
        "Her gün biraz daha fazla neşe ve mutluluk hissediyorum.",
        "Kendime olan güvenim, başarıya giden yolda en büyük rehberim.",
        "Kendimi sevmek, hayatımı daha fazla zevkli hale getiriyor.",
        "Hayatın güzelliklerini fark ediyor ve her anının tadını çıkarıyorum.",
        "Kendimi sevgiyle dolduruyor ve bu sevgiyi çevreme yayıyorum.",
        "Her gün biraz daha fazla özgürlük ve huzur hissediyorum.",
        "Kendimi olduğum gibi kabul ediyor ve kusurlarımı seviyorum.",
        "Geleceğe umutla bakıyor ve her gün daha fazla başarıya inanıyorum.",
        "Kendime güvenmek, her şeyin üstesinden gelmemi sağlar.",
        "Olumsuz düşünceleri geride bırakıyor ve olumlu bir gelecek inşa ediyorum.",
        "Her gün biraz daha fazla pozitif düşünceye sahip oluyorum ve bu beni daha da mutlu ediyor.",
        "Kendimi sevgiyle dolduruyor ve bu sevgiyi başkalarıyla paylaşıyorum.",
        "Başkalarının beni değerli hissetmemesi, benim değerli olduğum anlamına gelmez.",
        "Her gün biraz daha fazla özgüven kazanıyorum ve kendime olan inancımı güçlendiriyorum.",
        "Kendimi olduğum gibi kabul ediyor ve kusurlarımı seviyorum.",
        "Kendime olan inancım, en büyük gücüm.",
        "Her zorlukla karşılaştığımda, daha da güçleniyorum.",
        "Geleceğe umutla bakıyor ve en iyinin benim için olduğuna inanıyorum.",
        "Kendimi her gün biraz daha fazla geliştiriyorum ve büyüyorum.",
        "Olumlu düşünce tarzım, hayatımı daha da pozitif hale getiriyor.",
        "Her gün biraz daha fazla neşe ve mutluluk hissediyorum.",
        "Kendime olan güvenim, başarıya giden yolda en büyük rehberim.",
        "Kendimi sevmek, hayatımı daha fazla zevkli hale getiriyor.",
        "Hayatın güzelliklerini fark ediyor ve her anının tadını çıkarıyorum.",
        "Kendimi sevgiyle dolduruyor ve bu sevgiyi çevreme yayıyorum.",
        "Her gün biraz daha fazla özgürlük ve huzur hissediyorum.",
        "Kendimi olduğum gibi kabul ediyor ve kusurlarımı seviyorum.",
        "Geleceğe umutla bakıyor ve her gün daha fazla başarıya inanıyorum.",
        "Kendime güvenmek, her şeyin üstesinden gelmemi sağlar.",
        "Olumsuz düşünceleri geride bırakıyor ve olumlu bir gelecek inşa ediyorum.",
        "Her gün biraz daha fazla pozitif düşünceye sahip oluyorum ve bu beni daha da mutlu ediyor.",
        "Kendimi sevgiyle dolduruyor ve bu sevgiyi başkalarıyla paylaşıyorum.",
        "Başkalarının beni değerli hissetmemesi, benim değerli olduğum anlamına gelmez.",
        "Her gün biraz daha fazla özgüven kazanıyorum ve kendime olan inancımı güçlendiriyorum.",
        "Kendimi olduğum gibi kabul ediyor ve kusurlarımı seviyorum.",
        "Kendime olan inancım, en büyük gücüm.",
        "Her zorlukla karşılaştığımda, daha da güçleniyorum.",
        "Geleceğe umutla bakıyor ve en iyinin benim için olduğuna inanıyorum.",
        "Kendimi her gün biraz daha fazla geliştiriyorum ve büyüyorum.",
        "Olumlu düşünce tarzım, hayatımı daha da pozitif hale getiriyor.",
        "Her gün biraz daha fazla neşe ve mutluluk hissediyorum.",
        "Kendime olan güvenim, başarıya giden yolda en büyük rehberim.",
        "Kendimi sevmek, hayatımı daha fazla zevkli hale getiriyor.",
        "Hayatın güzelliklerini fark ediyor ve her anının tadını çıkarıyorum.",
        "Kendimi sevgiyle dolduruyor ve bu sevgiyi çevreme yayıyorum.",
        "Her gün biraz daha fazla özgürlük ve huzur hissediyorum.",
        "Kendimi olduğum gibi kabul ediyor ve kusurlarımı seviyorum.",
        "Geleceğe umutla bakıyor ve her gün daha fazla başarıya inanıyorum.",
        "Kendime güvenmek, her şeyin üstesinden gelmemi sağlar.",
        "Olumsuz düşünceleri geride bırakıyor ve olumlu bir gelecek inşa ediyorum.",
        "Her gün biraz daha fazla pozitif düşünceye sahip oluyorum ve bu beni daha da mutlu ediyor.",
        "Kendimi sevgiyle dolduruyor ve bu sevgiyi başkalarıyla paylaşıyorum.",
        "Başkalarının beni değerli hissetmemesi, benim değerli olduğum anlamına gelmez.",
        "Her gün biraz daha fazla özgüven kazanıyorum ve kendime olan inancımı güçlendiriyorum.",
        "Kendimi olduğum gibi kabul ediyor ve kusurlarımı seviyorum.",
        "Kendime olan inancım, en büyük gücüm.",
        "Her zorlukla karşılaştığımda, daha da güçleniyorum.",
        "Geleceğe umutla bakıyor ve en iyinin benim için olduğuna inanıyorum.",
        "Kendimi her gün biraz daha fazla geliştiriyorum ve büyüyorum.",
        "Olumlu düşünce tarzım, hayatımı daha da pozitif hale getiriyor.",
        "Her gün biraz daha fazla neşe ve mutluluk hissediyorum.",
        "Kendime olan güvenim, başarıya giden yolda en büyük rehberim.",
        "Kendimi sevmek, hayatımı daha fazla zevkli hale getiriyor.",
        "Hayatın güzelliklerini fark ediyor ve her anının tadını çıkarıyorum.",
        "Kendimi sevgiyle dolduruyor ve bu sevgiyi çevreme yayıyorum.",
        "Her gün biraz daha fazla özgürlük ve huzur hissediyorum.",
        "Kendimi olduğum gibi kabul ediyor ve kusurlarımı seviyorum.",
        "Geleceğe umutla bakıyor ve her gün daha fazla başarıya inanıyorum.",
        "Kendime güvenmek, her şeyin üstesinden gelmemi sağlar.",
        "Olumsuz düşünceleri geride bırakıyor ve olumlu bir gelecek inşa ediyorum.",
        "Her gün biraz daha fazla pozitif düşünceye sahip oluyorum ve bu beni daha da mutlu ediyor.",
        "Kendimi sevgiyle dolduruyor ve bu sevgiyi başkalarıyla paylaşıyorum.",
        "Başkalarının beni değerli hissetmemesi, benim değerli olduğum anlamına gelmez.",
        "Her gün biraz daha fazla özgüven kazanıyorum ve kendime olan inancımı güçlendiriyorum.",
        "Kendimi olduğum gibi kabul ediyor ve kusurlarımı seviyorum.",
        "Kendime olan inancım, en büyük gücüm.",
        "Her zorlukla karşılaştığımda, daha da güçleniyorum.",
        "Geleceğe umutla bakıyor ve en iyinin benim için olduğuna inanıyorum.",
        "Kendimi her gün biraz daha fazla geliştiriyorum ve büyüyorum.",
        "Olumlu düşünce tarzım, hayatımı daha da pozitif hale getiriyor.",
        "Her gün biraz daha fazla neşe ve mutluluk hissediyorum.",
        "Kendime olan güvenim, başarıya giden yolda en büyük rehberim.",
        "Kendimi sevmek, hayatımı daha fazla zevkli hale getiriyor.",
        "Hayatın güzelliklerini fark ediyor ve her anının tadını çıkarıyorum.",
        "Kendimi sevgiyle dolduruyor ve bu sevgiyi çevreme yayıyorum.",
        "Her gün biraz daha fazla özgürlük ve huzur hissediyorum.",
        "Kendimi olduğum gibi kabul ediyor ve kusurlarımı seviyorum.",
        "Geleceğe umutla bakıyor ve her gün daha fazla başarıya inanıyorum.",
        "Kendime güvenmek, her şeyin üstesinden gelmemi sağlar.",
        "Olumsuz düşünceleri geride bırakıyor ve olumlu bir gelecek inşa ediyorum.",
        "Her gün biraz daha fazla pozitif düşünceye sahip oluyorum ve bu beni daha da mutlu ediyor.",
        "Kendimi sevgiyle dolduruyor ve bu sevgiyi başkalarıyla paylaşıyorum.",
        "Başkalarının beni değerli hissetmemesi, benim değerli olduğum anlamına gelmez.",
        "Her gün biraz daha fazla özgüven kazanıyorum ve kendime olan inancımı güçlendiriyorum.",
        "Kendimi olduğum gibi kabul ediyor ve kusurlarımı seviyorum.",
        "Kendime olan inancım, en büyük gücüm.",
        "Her zorlukla karşılaştığımda, daha da güçleniyorum.",
        "Geleceğe umutla bakıyor ve en iyinin benim için olduğuna inanıyorum.",
        "Kendimi her gün biraz daha fazla geliştiriyorum ve büyüyorum.",
        "Olumlu düşünce tarzım, hayatımı daha da pozitif hale getiriyor.",
        "Her gün biraz daha fazla neşe ve mutluluk hissediyorum.",
        "Kendime olan güvenim, başarıya giden yolda en büyük rehberim.",
        "Kendimi sevmek, hayatımı daha fazla zevkli hale getiriyor.",
        "Hayatın güzelliklerini fark ediyor ve her anının tadını çıkarıyorum.",
        "Kendimi sevgiyle dolduruyor ve bu sevgiyi çevreme yayıyorum.",
        "Her gün biraz daha fazla özgürlük ve huzur hissediyorum.",
        "Kendimi olduğum gibi kabul ediyor ve kusurlarımı seviyorum."
    ]])
    
const getRandomWord = () => {
    const randomIndex = Math.floor(Math.random() * Sentences.length);
    return words[randomIndex];
  };
    
  }
//   export default class positiveSentences{ 

//   }